/**
 * Client-managed Qlik Sense platform adapter.
 *
 * Encapsulates all DOM interaction and Sense API calls specific to
 * Qlik Sense Enterprise on Windows (client-managed).
 */

import logger from '../util/logger';
import { getSelectors } from './selectors';

// ---------------------------------------------------------------------------
// Version detection
// ---------------------------------------------------------------------------

/**
 * Cached Sense version info.
 *
 * @type {{ version: string, releaseLabel: string } | null}
 */
let cachedVersionInfo = null;

/**
 * Detect the running Qlik Sense version by fetching the product-info manifest.
 *
 * @returns {Promise<{ version: string, releaseLabel: string } | null>}
 */
export async function getSenseVersion() {
    if (cachedVersionInfo) return cachedVersionInfo;

    try {
        const resp = await fetch('/resources/autogenerated/product-info.js');
        if (!resp.ok) {
            logger.warn(`product-info.js fetch failed: ${resp.status}`);
            return null;
        }

        const text = await resp.text();

        // Strip AMD wrapper: define([], function() { return <JSON>; });
        const jsonMatch = text.match(/return\s*(\{[\s\S]*\})\s*;?\s*\}\s*\)\s*;?\s*$/);
        if (!jsonMatch) {
            logger.warn('Could not parse product-info.js — unexpected format');
            return null;
        }

        const info = JSON.parse(jsonMatch[1]);
        const version = info?.composition?.version ?? null;
        const releaseLabel = info?.composition?.releaseLabel ?? '';

        if (version) {
            cachedVersionInfo = { version, releaseLabel };
            logger.info(`Sense version detected: ${version} (${releaseLabel})`);
            return cachedVersionInfo;
        }

        logger.warn('product-info.js did not contain a version');
        return null;
    } catch (err) {
        logger.warn('Sense version detection failed:', err);
        return null;
    }
}

// ---------------------------------------------------------------------------
// Code-path resolution
// ---------------------------------------------------------------------------

/**
 * Version-range-to-code-path mapping.
 *
 * @type {Array<{ minVersion: string, maxVersion: string, codePath: string }>}
 */
const versionRanges = [
    // Example: { minVersion: '15.0.0', maxVersion: '99.999.999', codePath: 'future' },
];

/**
 * Simple semver comparison.
 *
 * @param {string} a - Version string.
 * @param {string} b - Version string.
 * @returns {number} Negative if a < b, 0 if equal, positive if a > b.
 */
function compareVersions(a, b) {
    const pa = a.split('.').map(Number);
    const pb = b.split('.').map(Number);
    for (let i = 0; i < 3; i++) {
        const diff = (pa[i] || 0) - (pb[i] || 0);
        if (diff !== 0) return diff;
    }
    return 0;
}

/**
 * Resolve the code-path name for a given Sense version.
 *
 * @param {string | null} version - Sense version string.
 * @returns {string} Code-path name.
 */
export function resolveCodePath(version) {
    if (!version) return 'default';

    for (const range of versionRanges) {
        if (
            compareVersions(version, range.minVersion) >= 0 &&
            compareVersions(version, range.maxVersion) <= 0
        ) {
            return range.codePath;
        }
    }

    return 'default';
}

// ---------------------------------------------------------------------------
// Toolbar anchor
// ---------------------------------------------------------------------------

/**
 * Get the toolbar anchor element where the help button should be injected.
 *
 * @param {string} [codePath] - Code-path name.
 * @returns {Element | null} The toolbar anchor element, or null if not found.
 */
export function getToolbarAnchor(codePath) {
    const sels = getSelectors('client-managed', codePath);
    return document.querySelector(sels.toolbarAnchor);
}

/**
 * Get the toolbar anchor CSS selector string.
 *
 * @param {string} [codePath] - Code-path name.
 * @returns {string} CSS selector for the toolbar anchor.
 */
export function getToolbarAnchorSelector(codePath) {
    const sels = getSelectors('client-managed', codePath);
    return sels.toolbarAnchor;
}

// ---------------------------------------------------------------------------
// User context
// ---------------------------------------------------------------------------

/**
 * Cached user context.
 *
 * @type {{ userDirectory: string, userId: string } | null}
 */
let cachedUserContext = null;

/**
 * Fetch user context from the Qlik Sense proxy API.
 *
 * @returns {Promise<{ userDirectory: string, userId: string }>}
 */
export async function getUserContext() {
    if (cachedUserContext) return cachedUserContext;

    try {
        const resp = await fetch('/qps/user?targetUri=' + encodeURIComponent(window.location.href));
        if (!resp.ok) throw new Error(`HTTP ${resp.status}`);
        const data = await resp.json();
        cachedUserContext = {
            userDirectory: data.userDirectory || '',
            userId: data.userId || '',
        };
        logger.debug('CM user context loaded:', JSON.stringify(cachedUserContext));
        return cachedUserContext;
    } catch (err) {
        logger.warn('Failed to fetch CM user context:', err);
        return { userDirectory: '', userId: '' };
    }
}

// ---------------------------------------------------------------------------
// CSS injection
// ---------------------------------------------------------------------------

/**
 * Inject a CSS string into the document <head> as a <style> element.
 * Idempotent — if an element with the given ID already exists, it is skipped.
 *
 * @param {string} css - CSS string to inject.
 * @param {string} id - Unique ID for the <style> element.
 */
export function injectCSS(css, id) {
    if (document.getElementById(id)) return;

    const style = document.createElement('style');
    style.id = id;
    style.textContent = css;
    document.head.appendChild(style);
    logger.debug('Injected CSS:', id);
}
